---
- hosts: all
  vars:
  tasks:
    - name: Update APT package cache
      apt: 
        update_cache: yes 
        cache_valid_time: 3600
        force_apt_get: true

    - name: Upgrade APT to the latest packages
      apt:
        upgrade: safe
        force_apt_get: true

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
        force_apt_get: true
      with_items:
        - mitmproxy

